### ISSUE TITLE
Z-index misalignment

### ISSUE THREAD

**Issue by SlamaFR** [SlamaFR/BULB#1]
Sometimes, stop dots overlap below section elements.

![image](https://github.com/user-attachments/assets/1af8e09f-5689-4f4c-9a6d-78bb65ad0f58)

**Comment by Manu1400** [comment]
I don't reproduce this bug on
* Google Chrome
* Mozilla Firefox

**Comment by Manu1400** [comment]
documentation : https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements
proposal: use https://nuxt.com/docs/api/components/teleports
