### ISSUE TITLE
Invisible loop during exportations

### ISSUE THREAD

**Issue by Virgile-Mine** [SlamaFR/BULB#126]
**Describe the bug**

**To Reproduce**
1. Create a long line with a loop in each side.
2. Export the map
3. Open it and see the loop in the left is invisible. Ps : I tried to recreate it, along with the stops? But it's not working
**Expected behavior**
Normaly, the loop has to don't be invisible

**Screenshots**

**Desktop (please complete the following information):**
 - OS : Windows 7
 - Browser : Chrome
 - Version : Version 109.0.5414.120 (Build officiel) (64 bits)

**Additional context**
My line was created in an version, but it's not woking anyway
![image](https://github.com/user-attachments/assets/e79cdf38-9403-4219-8e9f-57fcf017447e)
![map (1)](https://github.com/user-attachments/assets/633b9b01-fd95-4cdb-85a5-c6608dd02035)
![map (2)](https://github.com/user-attachments/assets/7ef17c63-32e2-43ea-b342-97fe89d89222)
![map (3)](https://github.com/user-attachments/assets/7430f063-ebd3-492f-b4d6-491e9cf50c9c)
![map (4)](https://github.com/user-attachments/assets/657252d3-92e5-4dda-bfd2-51463902904b)
![map](https://github.com/user-attachments/assets/f3d6dbd8-2a66-46f2-ba1b-2b886d906531)

**Comment by Virgile-Mine** [comment]
[bus_51.json](https://github.com/user-attachments/files/18115123/bus_51.json)
![image](https://github.com/user-attachments/assets/1b08afe5-c3ee-42e6-89b4-ce348a95ef88)
Here is the save file and the toobleshoting informations

**Comment by SlamaFR** [comment]
On va continuer en français.. 

Je vois que tu utilises Chrome 109 et on en est quand même à la version 131, donc si tu peux utiliser une version plus récente ça devrait régler le problème.

**Comment by Virgile-Mine** [comment]
Pas de soucis. Je ne peux pas mettre à jour Chrome. La 109 est la dernière version compatible avec Windows 7 😢. Ce qui m'étonne, c'est que ça fonctionnait bien avant la mise à jour. Si je ne me trompe pas, le seul navigateur encore mis à jour sur Windows 7, c'est Firefox, qui n'est pas compatible avec Bulb.

**Comment by SlamaFR** [comment]
Je peux toujours essayer de déployer la version précédente dans un nouvel environnement comme ça tu testes et tu me dis :)

**Comment by SlamaFR** [comment]
Tiens je t'ai déployé la version précédente ici : https://bulb-prev.slama.io/editor/

**Comment by Virgile-Mine** [comment]
J'ai essayé avec l'autre version. Ça fonctionne. J'ai recréé une autre ligne avec le même nombre d'arrêt et la même structure sur la nouvelle version, , marche pas
![map (1)](https://github.com/user-attachments/assets/a139c9f2-a7ae-4620-82ae-5df639bb7a41)

**Comment by SlamaFR** [comment]
J'ai tenté de mon côté sur plusieurs versions anciennes de Chrome sur une VM Win10 et aucun problème à signaler. Ça doit donc probablement venir de Windows 7 je suppose...

**Comment by Virgile-Mine** [comment]
Dans ce cas. C'est probable. Tampi. Y a t il des choses que je pourrais faire afin de contribuer au projet?
