### ISSUE TITLE
Onglet d'image non affichée dans favoris

### ISSUE THREAD

**Issue by MollussPoussachad** [SlamaFR/BULB#127]
**Describe the bug**d

**To Reproduce**
1. Créer une ligne
2. l'exporter
3. Ajouter l'onglet de l'image du plan aux favoris

**Expected behavior**
Je dois voir l'image dans mes favoris

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: Version 131.0.6778.140 (Build officiel) (64 bits)

**Additional context**
Je pense qu'il est créer avant la 1.4.0

**Comment by SlamaFR** [comment]
J'ai rien compris
