### ISSUE TITLE
Add some french logos (Ouigo, ...)

### ISSUE THREAD

**Issue by Manu1400** [SlamaFR/BULB#36]
[nicolaswurtz/signalisation-rfn-svg](https://github.com/nicolaswurtz/signalisation-rfn-svg) give Eurostar, TGV inOui, Intercités, TGV Lyria, OUIGO, Thalys, Transilien logos

## example(s)
* [OUIGO logo (in SVG)](https://github.com/nicolaswurtz/signalisation-rfn-svg/blob/ce909ca32bab66b7e333d9f6441a6ddcc949af0d/pictogrammes/logos/ouigo.svg?plain=1)

**Comment by SlamaFR** [comment]
This will be achievable when custom pictograms are supported.
