### ISSUE TITLE
Last update broke the station selection

### ISSUE THREAD

**Issue by simeoncapy** [SlamaFR/BULB#58]
Since the last update, the selection of the station is bugged, the cursor seems to select the stations on the right and not under it. Then, on some stations it is impossible to select the transfer icon anymore.

For example, here my cursor is on the Mulhouse station, but the next branch is highlighted, and the transfer icon is not appearing.
![image](https://github.com/user-attachments/assets/97fa7296-a963-4068-992e-e68428c6a577)

**Comment by SlamaFR** [comment]
Once again, that's because you inserted too many branches... You only need one.

**Comment by simeoncapy** [comment]
There is only one branch

**Comment by simeoncapy** [comment]
Haaaaaa, I understood what you mean! The branch is not the connection between the stations, we should move the stations on one branch only.

Indeed, it's tricky. I thought you need to use the branch as a link.

**Comment by SlamaFR** [comment]
Yes I know it not very intuitive, but I'm trying my best to make it as simple as possible. 

However it seems to be still a bit unfriendly.

**Comment by simeoncapy** [comment]
Yeah, I understand, it's hard to find intuitive UX.

Maybe by making the first branch longer, to understand that you have to put the station on it? It's also hard for me to think something intuitive ^^

**Comment by SlamaFR** [comment]
Fixed
