### ISSUE TITLE
Unable to create new line numbers

### ISSUE THREAD

**Issue by alexandredoyen29** [SlamaFR/BULB#87]
**Describe the bug**
When I click on "Indices personnalisés", it is not possible to add new line.
I tried to use an already created line as template (Ligne 7) before doing this.

**To Reproduce**
1. Load the Ligne 7 template
2. Modify some elements of the line
3. Try to create a new custom line number

**Expected behavior**
A window asking for new line information

**Screenshots**
![image](https://github.com/user-attachments/assets/ed1cd9b5-de4e-4479-b70f-2fe8478e60a7)

**Comment by SlamaFR** [comment]
Since you are running in development mode, I think it's an auto-import issue. I suggest you run `pnpm nuxi prepare` then restart the dev server.

**Comment by alexandredoyen29** [comment]
Thank you for your answer !

Unfortunately, your answer does not solve the problem.
I ran this sequence of commands to build BULB :
- `./node_modules/pnpm/bin/pnpm.cjs nuxi prepare`
- `./node_modules/pnpm/bin/pnpm.cjs build`
- `node .output/server/index.mjs`

Sorry, I'm not an expert in JS and web development 😇

**Comment by SlamaFR** [comment]
Oh, BULB is not meant to be served with a Node server.  If you want to run it locally, you should only run `pnpm run dev`.

**Comment by alexandredoyen29** [comment]
Even by launching it with `pnpm`, it does not work :/
I also tried with Chromium, but it does not work too.

**Comment by SlamaFR** [comment]
In any ways, this sounds like a local configuration or environment problem. I'll put this issue on hold for now.

If you've not modified the code yet, you should delete and clone the repository again. Otherwise, delete the `node_modules` and `nuxt` directories, and run `pnpm i` and `pnpm run dev`

**Comment by alexandredoyen29** [comment]
Ok, I'll try this

**Comment by SlamaFR** [comment]
Turns out someone else has the same issue. I will investigate this.

**Comment by SlamaFR** [comment]
It should be fixed now, just pull the latest commits and give it a shot.

**Comment by alexandredoyen29** [comment]
Yep, it works right now !
Thank you ;)

![image](https://github.com/user-attachments/assets/00914c59-106f-4522-bb16-09be0ea47335)
