### ISSUE TITLE
Problems while opening project 

### ISSUE THREAD

**Issue by LEX2050** [SlamaFR/BULB#98]
Hi,

I have created many project on the following website :

https://bulb.slama.io/editor/

While opening my latest project (06.10.2024) I encounter a problem. 

They are all blank. All details have been wiped out.

Can you help solving the issue?

Cheers,

Alain

**Comment by LEX2050** [comment]
What menu?

**Comment by SlamaFR** [comment]
On the left pane, the button with a small wrench, you can just screenshot the popup.

**Comment by LEX2050** [comment]
![Capture d’écran 2024-10-21 182427](https://github.com/user-attachments/assets/725d3a66-4beb-4c43-8feb-7cf2f613e530)

**Comment by LEX2050** [comment]
So are all my project done under Pre 1.3.0-alpha version are lost?!

**Comment by SlamaFR** [comment]
As the application told you when loading your project, it is indeed no longer supported. I know this is unfortunate, but it's an issue to expect when using a software in alpha phase. People expect me to add new features, and I need to change things that break older versions to do so.

I will probably provide a project migrator later to restore older projects. You can still save the obsolete project for later.

Really sorry for the inconvenience...

**Comment by LEX2050** [comment]
I did save them. I understand that it was an alpha version , yet, this projet were only two weeks old! This is, indeed, very unfortunate
